name: PR Check

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: CI Success
        run: echo "CI Pipeline Passed!"